global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
    log-level: info
    ics20-memo-limit: 0
    max-receiver-size: 150
chains:
    terpnetworktestnet:
        type: cosmos
        value:
            key-directory: /.relayer/keys/<your-keys>
            key: terptestnet-1
            chain-id: 90u-4
            rpc-addr: https://terp-testnet-rpc.itrocket.net:443
            account-prefix: terp
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.5uthiolx
            min-gas-amount: 500000
            max-gas-amount: 10000000
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths: